### ISSUE TITLE
React.js build for production

### ISSUE THREAD

**Issue by rpereira** [arkency/scaffold-to-react#2] opened 2016-03-28 12:43 UTC
@Killavus, I was taking a look at [your commits](https://github.com/arkency/scaffold-to-react/commits/newest-20160324) to the `newest-20160324` branch, and something caught my attention. While in production environment, wouldn't you want to [configure the React build](https://github.com/arkency/scaffold-to-react/blob/a3161c1217aeb66b76c2d16d2b26e52834715ed9/config/environments/production.rb#L80) as `production` instead of `development`?

Cheers.

**Comment by Killavus** [comment] 2016-03-28 12:46
Yeah. A simple mistake. I'll fix that after easter :).

Have a nice holidays!
Marcin

**Comment by rpereira** [comment] 2016-03-28 12:49
Happy Holidays!

**Comment by Killavus** [comment] 2016-03-29 07:36
Hey, the issue is fixed in the following commit: https://github.com/arkency/scaffold-to-react/commit/c7c19680140157ef2ef9319d8153b61852fa99c6

Thank you for pointing it out!

Have a nice day,
Marcin

**Closed as completed by Killavus** 2016-03-29 07:36 UTC
